Add trasition transform to book list
wolox-training/st-angular pull request #12
Opened 2020-04-14 21:40 UTC by blacksam07

## Summary
- Add transition transform to item list

## Trello Card

[35-transitions](https://trello.com/c/TuuaSnSD/35-transitions)

## Screenshot

![Uploading transition-list.gif…]()

2020-04-15 15:02 UTC, CrisVega08 requested changes

2020-04-15 15:02 UTC, CrisVega08 commented on scss/index.scss
> +.list-item:hover {
Use sass Nesting

2020-04-15 15:02 UTC, CrisVega08 commented on scss/index.scss
> +  transition: transform 0.5s;
Define transition on .list-item class

2020-04-15 15:02 UTC, CrisVega08 commented on scss/index.scss
> +.list-item:hover {
Also remember use :: for pseudo elements

2020-04-15 19:07 UTC, betoobernal commented on scss/index.scss
>    margin: 15px 15px;
assing unary value will be enough. Only 15px. 😅

2020-04-15 21:46 UTC, CrisVega08 approved these changes

2020-04-17 15:06 UTC, betoobernal approved these changes

2020-04-17 16:47 UTC, merged