Add angular project
wolox-training/st-angular pull request #14
Opened 2020-04-16 17:34 UTC by blacksam07

## Summary
- Install Angular CLI
- Create angular project

## Trello card
[3-angular-cli](https://trello.com/c/YhVOGmJy/3-angular-cli)

2020-04-17 17:44 UTC, betoobernal commented on tslint.json
> +}
add space to the end

2020-04-17 17:44 UTC, betoobernal commented on e2e/protractor.conf.js
> +};
same

2020-04-17 17:44 UTC, betoobernal commented on angular.json
> +}
same

2020-04-17 17:58 UTC, blacksam07 commented on tslint.json
> +}
auto-generated by CLI

2020-04-17 17:59 UTC, blacksam07 commented on e2e/protractor.conf.js
> +};
auto-generate

2020-04-17 19:50 UTC, CrisVega08 requested changes

2020-04-17 19:50 UTC, CrisVega08 commented on e2e/src/app.e2e-spec.ts
> +import { AppPage } from './app.po';
Delete this file, you are not going to do test

2020-04-17 19:50 UTC, CrisVega08 commented on src/app/app.component.spec.ts
> +import { TestBed, async } from '@angular/core/testing';
Same delete

2020-04-17 20:16 UTC, betoobernal commented on src/app/app.module.ts
> +  providers: [],
if it's empty is better to remove it.

2020-04-21 15:09 UTC, CrisVega08 approved these changes

2020-04-21 18:07 UTC, betoobernal approved these changes

2020-04-22 15:35 UTC, merged