Add authentication view with data validations
wolox-training/st-angular pull request #16
Opened 2020-04-21 00:08 UTC by blacksam07

## Summary
- Add authentication view (login and register) with data validations

## Trello Card
[8-register-layout](https://trello.com/c/yTbuElBU/8-register-layout)

## Screenshots

![image](https://user-images.githubusercontent.com/50454914/79809432-0d219a00-8336-11ea-8653-f38c22c927a8.png)

![authentication-min](https://user-images.githubusercontent.com/50454914/79810995-2debee80-833a-11ea-942d-05b45e3506c7.gif)

2020-04-21 16:48 UTC, CrisVega08 requested changes

2020-04-21 16:48 UTC, CrisVega08 commented on src/app/app.component.html
>  <div>
Why empty div?

2020-04-21 16:48 UTC, CrisVega08 commented on src/app/app.component.ts
> +  isLogin = 'true';
Why use a string?, try to use boolean

2020-04-21 16:48 UTC, CrisVega08 commented on src/app/app.component.html
>  <router-outlet></router-outlet>
You don't are using routes so delete it.

2020-04-21 16:48 UTC, CrisVega08 commented on src/app/authentication/authentication.component.html
> -<ng-content></ng-content>
Why do you delete ??
I remember that card says you use a ng-content for showing maquetado

2020-04-21 16:48 UTC, CrisVega08 commented on src/app/authentication/authentication.component.scss
> +}
Add empty line

2020-04-21 16:48 UTC, CrisVega08 commented on src/app/authentication/authentication.component.ts
> +    value.user.locale = 'en'
you don't need this line, when you create form, you can add a default value for locate

2020-04-21 16:48 UTC, CrisVega08 commented on src/app/authentication/authentication.component.html
> +  <form [formGroup]="authForm" (ngSubmit)="onSubmit(authForm.value)" [ngClass]="{'login-form': true, 'login-form-sign-up': !isLogin}" >
when use reactive form don't need pass value on function 
```suggestion
  <form [formGroup]="authForm" (ngSubmit)="onSubmit()" [ngClass]="{'login-form': true, 'login-form-sign-up': !isLogin}" >
```

2020-04-21 16:48 UTC, CrisVega08 commented on src/app/authentication/authentication.component.ts
> +        password_confirmation: [''],
put validation required

2020-04-21 16:48 UTC, CrisVega08 commented on src/app/authentication/authentication.component.html
> +      <div *ngIf="isLogin else signUp">
separate this logic on two components one sign-up and other sign-in and use ng content-show the view

2020-04-21 16:48 UTC, CrisVega08 commented on src/app/authentication/authentication.component.ts
> +  let pass = group.get('password').value;
Use const and check indentation

2020-04-21 16:48 UTC, CrisVega08 commented on src/app/authentication/authentication.component.ts
> +  checkInput(input: string) {
Great :clap

2020-04-21 16:48 UTC, CrisVega08 commented on src/app/authentication/authentication.component.ts
> +  constructor(private formBuilder: FormBuilder) {
Don't use constructor form, try to build form on onInit cycle

2020-04-21 16:48 UTC, CrisVega08 commented on src/app/authentication/authentication.component.ts
> +  checkPasswords(group: FormGroup) {
```suggestion
  checkPasswords(group: : AbstractControl) {
```
Where do you use this function??

2020-04-21 16:48 UTC, CrisVega08 commented on src/app/authentication/authentication.component.ts
> +  label_button_up = 'Login';
Use camelCase

2020-04-21 16:48 UTC, CrisVega08 commented on src/app/authentication/authentication.component.ts
> +  label_button_down = 'Sign Up';
Same

2020-04-21 16:48 UTC, CrisVega08 commented on src/app/authentication/authentication.component.ts
> +    if (!this.isLogin) this.authForm.get('user').get('password_confirmation').setValidators([Validators.required])
make this on onInit after change components to use ng-content 
```suggestion
    if (!this.isLogin) this.authForm.get('user.password_confirmation').setValidators([Validators.required])
```

2020-04-21 16:48 UTC, CrisVega08 commented on src/app/authentication/authentication.component.ts
> +        const control = formGroup.controls[controlName];
check indentation

2020-04-21 16:48 UTC, CrisVega08 commented on src/app/authentication/authentication.component.ts
> +  mustMatch(controlName: string, matchingControlName: string) {
I dont understand this function I prefer that you use checksPasswords

2020-04-21 18:21 UTC, betoobernal commented on src/app/authentication/authentication.component.html
> +      <button class="login-button" type="submit" [disabled]="!authForm.valid">{{label_button_up}}</button>
**only as note instructive**: you can to use `authForm.invalid`

2020-04-21 18:34 UTC, betoobernal commented on src/app/authentication/authentication.component.ts
> +  return pass === confirmPass ? null : { notSame: true }
you can use an interruptor `pass === confirmPass && { notSame: true }`, unless that you will actually need to return a `null` value.

2020-04-21 18:37 UTC, betoobernal commented on src/app/authentication/authentication.component.ts
> +    if (!this.isLogin) this.authForm.get('user').get('password_confirmation').setValidators([Validators.required])
```suggestion
    if (!this.isLogin) {
        this.authForm.get('user')
            .get('password_confirmation')
            .setValidators([Validators.required])
    }
```

close it better in a block

2020-04-21 18:44 UTC, betoobernal commented on src/app/authentication/authentication.component.html
> +        <input class="form-input" id="apellido" type="text" formControlName="last_name">
what use do you give to `id` attribute?

2020-04-21 18:50 UTC, blacksam07 commented on src/app/app.component.ts
> +  isLogin = 'true';
this code will be deleted in the future

2020-04-22 23:02 UTC, CrisVega08 requested changes

2020-04-22 23:02 UTC, CrisVega08 commented on src/app/app.component.ts
>    title = 'wolox-books';
Delete this property you didn't use

2020-04-22 23:02 UTC, CrisVega08 commented on src/app/app.component.ts
> +  encapsulation: ViewEncapsulation.None
I  think you don't viewEncapsulation

2020-04-22 23:02 UTC, CrisVega08 commented on src/app/authentication/authentication.component.scss
> +@import '../../styles.scss';
Delete you only need and try to use absolute paths
```suggestion
@import '../../_colors.scss';
```

2020-04-22 23:02 UTC, CrisVega08 commented on src/app/authentication/authentication.component.scss
> +    position: absolute;
which is the reference for this position?

2020-04-22 23:02 UTC, CrisVega08 commented on src/app/button/button.component.scss
> +@import '../../styles.scss';
Same

2020-04-22 23:02 UTC, CrisVega08 commented on src/app/button/button.component.scss
> +    position: absolute;
Same about reference

2020-04-22 23:02 UTC, CrisVega08 commented on src/app/button/button.component.ts
> +  bClass: string = 'primary';
one line

2020-04-22 23:02 UTC, CrisVega08 commented on src/app/button/button.component.ts
> +  @Input('type')
same

2020-04-22 23:02 UTC, CrisVega08 commented on src/app/signup/signup.component.html
> +    <div formGroupName="user">
Why you don't use (ngSubmit)="onSubmit()"

2020-04-22 23:02 UTC, CrisVega08 commented on src/app/signup/signup.component.html
> +  <app-button [class]="'secondary'" [value]="'Login'"></app-button>
Dont do binding when is a constant 
```suggestion
  <app-button class='secondary' value="Login'></app-button>
```

2020-04-22 23:02 UTC, CrisVega08 commented on src/app/signup/signup.component.html
> +  <app-button (bClick)="onSubmit(authForm.value)" [value]="'Sign Up'" [disabled]="authForm.invalid" [borderLine]="true"></app-button>
```suggestion
  <app-button type="submit" value="Sign Up" [disabled]="authForm.invalid" [borderLine]="true"></app-button>
```

2020-04-22 23:02 UTC, CrisVega08 commented on src/app/signup/signup.component.scss
> +@import '../../styles.scss';
Same here

2020-04-22 23:02 UTC, CrisVega08 commented on src/app/signup/signup.component.ts
> +        first_name: '',
use camelCase always

2020-04-22 23:02 UTC, CrisVega08 commented on src/app/signup/signup.component.ts
> +        last_name: '',
Same camelCase

2020-04-22 23:02 UTC, CrisVega08 commented on src/app/signup/signup.component.ts
> +        password_confirmation: [''],
same

2020-04-22 23:02 UTC, CrisVega08 commented on src/app/button/button.component.ts
> +  @Input('value')
very bad name jajaj i suggest label or text

2020-04-22 23:02 UTC, CrisVega08 commented on src/app/button/button.component.ts
> +  @Input('borderLine')
one line

2020-04-22 23:02 UTC, CrisVega08 commented on src/app/button/button.component.ts
> +    if (this.borderLine) this.bClass = `${this.bClass} border-line`
Do this in template

2020-04-24 15:58 UTC, CrisVega08 requested changes

2020-04-24 15:58 UTC, CrisVega08 commented on src/app/authentication/authentication.component.html
> +  <div class="authentication-form" >
problems with indentation

2020-04-24 15:58 UTC, CrisVega08 commented on src/app/authentication/authentication.component.scss
> +@import '_colors';
Nice

2020-04-24 15:58 UTC, CrisVega08 commented on src/app/button/button.component.ts
> +  @Input('class')
I forget say you, don't make aliases, change on names o inputs for example 

@Input() class = 'primary';

2020-04-24 15:58 UTC, CrisVega08 commented on src/app/signup/signup.component.html
> +  <form [formGroup]="authForm" (ngSubmit)="onSubmit(authForm.value)">
Dont put value, obtain it on component with this.authForm.value
```suggestion
  <form [formGroup]="authForm" (ngSubmit)="onSubmit()">
```

2020-04-24 15:58 UTC, CrisVega08 commented on src/app/signup/signup.component.html
> +    <app-button [type]="'submit'" [label]="'Sign Up'" [disabled]="authForm.invalid" [oneLine]="true"></app-button>
Remember when value is a string don't do binding
```suggestion
    <app-button type="submit" label="Sign Up" [disabled]="authForm.invalid" [oneLine]="true"></app-button>
```

2020-04-24 15:58 UTC, CrisVega08 commented on src/app/signup/signup.component.html
> +    <app-button [class]="'secondary'" [label]="'Login'"></app-button>
Same

2020-04-24 15:58 UTC, CrisVega08 commented on src/app/signup/signup.component.ts
> +        firstName: '',
put required validator

2020-04-24 15:58 UTC, CrisVega08 commented on src/app/signup/signup.component.ts
> +        lastName: '',
Same

2020-04-24 15:58 UTC, CrisVega08 commented on src/app/signup/signup.component.ts
> +    value.user.locale = 'en'
You don't need it, you are setting at creating form

2020-04-24 22:00 UTC, betoobernal commented on src/app/signup/signup.component.ts
> +
these methods could are in a utils file 🤔

2020-04-27 15:20 UTC, CrisVega08 requested changes

2020-04-27 15:20 UTC, CrisVega08 commented on src/app/signup/signup.component.ts
> +    this.authForm = this.formBuilder.group({
other thing remove this on constructor() and put inside onInit().

2020-04-27 20:16 UTC, betoobernal commented on src/app/helpers/utils/utils.ts
> +  let res: Object = {};
the res variable doesn't need a typing, she gets one implicit when it's assigned.

2020-04-28 14:53 UTC, CrisVega08 approved these changes

2020-04-29 15:25 UTC, betoobernal approved these changes

2020-04-29 22:25 UTC, merged