Add user service
wolox-training/st-angular pull request #18
Opened 2020-04-27 19:29 UTC by blacksam07

## Summary
- Add user service
- Add user structure

## Trello card
[7-registration-api-integration](https://trello.com/c/8o0olNEK/7-registration-api-integration)

## Screenshots

<img width="1680" alt="Screen Shot 2020-04-27 at 13 38 10" src="https://user-images.githubusercontent.com/50454914/80412328-553f4000-8893-11ea-991a-6e75c1221ea9.png">

<img width="1680" alt="Screen Shot 2020-04-27 at 13 38 40" src="https://user-images.githubusercontent.com/50454914/80412338-57090380-8893-11ea-8449-33358ebf4b85.png">

2020-04-27 20:19 UTC, betoobernal commented on src/app/screens/authentication/components/signup/signup.component.ts
> +  constructor(private formBuilder: FormBuilder, public http: HttpClient, private userService: UserService) { }
the accessors should be privates.

2020-04-27 20:21 UTC, betoobernal commented on src/app/screens/authentication/components/signup/signup.component.ts
>      this.authForm.reset();
reset the form when the subscription is fulfilled

2020-04-27 20:21 UTC, betoobernal commented on src/app/services/user.service.ts
> +
remove white spaces

2020-04-27 20:22 UTC, betoobernal commented on src/app/services/user.ts
> +}
add a newline at end

2020-04-28 15:01 UTC, CrisVega08 requested changes

2020-04-28 15:01 UTC, CrisVega08 commented on src/app/screens/authentication/components/signup/signup.component.ts
> +  constructor(private formBuilder: FormBuilder, private http: HttpClient, private userService: UserService) { }
why HttpClient Here??

2020-04-29 15:34 UTC, betoobernal commented on src/app/services/user.service.ts
> +        map((data: User) => data),
why are you using this mapping? 🤔

2020-04-29 15:44 UTC, betoobernal commented on src/app/services/user.service.ts
> +  apiUrl = `${environment.apiUrl}/users`;
should it be private?

2020-05-04 14:58 UTC, betoobernal approved these changes

2020-05-04 15:26 UTC, CrisVega08 approved these changes

2020-05-04 15:57 UTC, merged