Add routing to application
wolox-training/st-angular pull request #19
Opened 2020-04-28 00:43 UTC by blacksam07

## Summary
- Add routing to application
- Add login component

## Trello card
[10-angular-router](https://trello.com/c/foOkpU9L/10-angular-router)

## Screenshots
![routing-min](https://user-images.githubusercontent.com/50454914/80434391-4c646380-88bf-11ea-9ba9-245dd82a241f.gif)

2020-04-28 15:04 UTC, CrisVega08 requested changes

2020-04-28 15:04 UTC, CrisVega08 commented on src/app/screens/authentication/components/signup/signup.component.html
> +    <app-button class="secondary" label="Login" (bClick)="goToLogin()"></app-button>
try to use routerLink on template

2020-04-29 21:23 UTC, CrisVega08 approved these changes

2020-05-06 03:11 UTC, betoobernal approved these changes

2020-05-06 15:38 UTC, merged