Feature/auth guard
wolox-training/st-angular pull request #22
Opened 2020-05-04 22:57 UTC by blacksam07

## Summary

- Add auth and unauth guards
- Add modules to auth and unauth
- Add new component bookList

## Trello card
[15-auth-guard-unauth-guard](https://trello.com/c/tUnYKWcS/15-auth-guard-unauth-guard)

## Screenshots

![guard-min](https://user-images.githubusercontent.com/50454914/81021327-89d16f80-8e30-11ea-82de-a82ab464202e.gif)

2020-05-05 21:58 UTC, CrisVega08 requested changes
Nice work 👏

2020-05-05 21:58 UTC, CrisVega08 commented on src/app/modules/auth/auth.component.scss
> + margin-top: 70px;
check indentation

2020-05-05 21:58 UTC, CrisVega08 commented on src/app/guards/auth.guard.ts
> +  providedIn: 'root'
ok, you are providing twice because in this line you say inject on root, but on app,module.ts you are providing the service again

2020-05-05 21:58 UTC, CrisVega08 commented on src/app/guards/unauth.guard.ts
> +  providedIn: 'root'
Same

2020-05-05 21:58 UTC, CrisVega08 commented on src/app/modules/auth/auth.module.ts
> +
delete

2020-05-05 21:58 UTC, CrisVega08 commented on src/app/modules/auth/auth.module.ts
> +
delete

2020-05-05 21:58 UTC, CrisVega08 commented on src/app/modules/auth/auth.module.ts
> +    { path: 'books', component: BookListComponent }
check indentation

2020-05-05 21:58 UTC, CrisVega08 commented on src/app/modules/unauth/unauth.component.ts
> +  }
same line

2020-05-05 21:58 UTC, CrisVega08 commented on src/app/screens/book-list/book-list.component.ts
> +  constructor() { }
```suggestion
  constructor() {}
```

2020-05-06 03:19 UTC, betoobernal commented on src/app/modules/auth/auth.module.ts
> +  declarations: [],
remove

2020-05-06 03:19 UTC, betoobernal commented on src/app/modules/unauth/unauth.module.ts
> +  declarations: [],
remove

2020-05-06 03:24 UTC, betoobernal commented on src/app/services/user.service.ts
> +    if (this.store.get('access-token') &&  this.store.get('client') && this.store.get('uid')) {
You can get luxuries for you, for instance, does the get method receive a string or array of values.

2020-05-06 03:25 UTC, betoobernal commented on src/app/services/user.service.ts
> +    return false;
Use a ternary operator:

```suggestion
 return this.store.get('access-token') &&  this.store.get('client') && this.store.get('uid')
```

2020-05-07 15:59 UTC, CrisVega08 requested changes

2020-05-07 15:59 UTC, CrisVega08 commented on src/app/modules/auth/auth.module.ts
> +const routes: Routes = [
I suggest to create a file for routes

2020-05-07 15:59 UTC, CrisVega08 commented on src/app/modules/unauth/unauth.module.ts
> +const routes: Routes = [
Same

2020-05-08 14:51 UTC, betoobernal commented on src/app/services/user.service.ts
> +    return this.store.get('access-token', 'client', 'uid').length === 3
nice ❤️

2020-05-08 14:52 UTC, betoobernal approved these changes

2020-05-08 17:38 UTC, CrisVega08 approved these changes

2020-05-08 20:43 UTC, merged