Feature/book list
wolox-training/st-angular pull request #23
Opened 2020-05-05 01:15 UTC by blacksam07

## Summary
- Add tokenInterceptor to add headers
- Add view to bookList
- Add book service 

## Trello Card 
[12-book-list-auth-header](https://trello.com/c/S13XU2Tj/12-book-list-auth-header)

## Screenshots

![book_list-min](https://user-images.githubusercontent.com/50454914/81027543-d2465880-8e43-11ea-9254-653a7f61abf3.gif)

2020-05-05 22:04 UTC, CrisVega08 requested changes

2020-05-05 22:04 UTC, CrisVega08 commented on src/app/screens/book-list/book-list.component.html
> +  <ng-template ngFor let-book [ngForOf]="books" let-i="index">
is unnecessary this ng-template delete

2020-05-05 22:04 UTC, CrisVega08 commented on src/app/screens/book-list/book-list.component.html
> +    <div class="list-item">
```suggestion
    <div *ngFor="let book of books" class="list-item">
```

2020-05-05 22:04 UTC, CrisVega08 commented on src/app/services/book.service.ts
> +  providedIn: 'root'
Are you sure of providing this service on all app or only in auth.module?

2020-05-05 22:04 UTC, CrisVega08 commented on src/app/services/book.service.ts
> +  getBooks (): Observable<any> {
```suggestion
  getBooks(): Observable<any> {
```

2020-05-06 03:31 UTC, betoobernal commented on src/app/screens/book-list/book-list.component.ts
> +      })
use destructuring
```suggestion
    this.bookService.getBooks()
      .subscribe(({page}) => {
        this.books = page;
      })
```

2020-05-06 03:32 UTC, betoobernal commented on src/app/token.interceptor.ts
> +        }
nice

2020-05-07 16:03 UTC, CrisVega08 approved these changes

2020-05-07 16:03 UTC, CrisVega08 commented on src/app/screens/book-list/book-list.component.html
> +  <div *ngFor="let book of books"  class="list-item">
```suggestion
  <div *ngFor="let book of books" class="list-item">
```

2020-05-07 16:03 UTC, CrisVega08 commented on src/app/services/book.service.ts
> +  constructor(private http: HttpClient) { }
```suggestion
  constructor(private http: HttpClient) {}
```

2020-05-08 14:54 UTC, betoobernal approved these changes

2020-05-08 20:43 UTC, merged