Add shopping cart service
wolox-training/st-angular pull request #26
Opened 2020-05-05 21:50 UTC by blacksam07

## Summary

- Add Shopping cart service 

## Trello card 

[22-component-communication](https://trello.com/c/AW04E5wB/22-component-communication)

## Screenshots 

![shopping-cart-min](https://user-images.githubusercontent.com/50454914/81119477-71c12500-8ef0-11ea-86c8-35189767dfc4.gif)

2020-05-05 22:18 UTC, CrisVega08 requested changes

2020-05-05 22:18 UTC, CrisVega08 commented on src/app/modules/auth/auth.component.scss
> +  width: 150px;
sort

2020-05-05 22:18 UTC, CrisVega08 commented on src/app/modules/auth/auth.component.ts
> +  count = 1;
why count is setting in 1?

2020-05-05 22:18 UTC, CrisVega08 commented on src/app/services/shopping-cart.service.ts
> +  providedIn: 'root'
why in root?

2020-05-05 22:18 UTC, CrisVega08 commented on src/app/services/shopping-cart.service.ts
> +  private books = new BehaviorSubject(JSON.parse(this.localStorage.get('shoppingBooks')) || []);
I dont like this, i suggest and empty array

2020-05-05 22:28 UTC, blacksam07 commented on src/app/modules/auth/auth.component.ts
> +  count = 1;
Jajajaja sorry 😐 it was a test

2020-05-07 16:12 UTC, CrisVega08 requested changes

2020-05-07 16:12 UTC, CrisVega08 commented on src/app/modules/auth/auth.component.ts
> +    this.shoppingService.shoppingBooks.subscribe(books => this.count = books.length);
ok but you need to unsubscribe on component destroy.

2020-05-07 16:12 UTC, CrisVega08 commented on src/app/modules/auth/auth.module.ts
> +    ShoppingCartService
why this?

2020-05-07 16:12 UTC, CrisVega08 commented on src/app/screens/book-list/book-list.component.html
> +    <div *ngFor="let book of books | filter:filterValue"  class="list-item">
```suggestion
    <div *ngFor="let book of books | filter:filterValue" class="list-item">
```

2020-05-08 15:11 UTC, betoobernal commented on src/app/modules/auth/auth.component.html
> +    <a href="" class="shopping-cart">
why do you use the anchor without `href` value? 🤔

2020-05-08 15:19 UTC, betoobernal commented on src/app/screens/book-list/book-list.component.ts
> +      this.shoppingService.shoppingBooks.subscribe(books => this.shoppingBooks = books);
you should work with all response data at the same time. Check [this](https://rxjs-dev.firebaseapp.com/api/index/function/forkJoin) 👀

2020-05-08 15:24 UTC, betoobernal commented on src/app/services/shopping-cart.service.ts
> +    this.books.next(this.books.value);
```suggestion
    const books = [...this.books.value, {...book}];
    this.books.next(books);
```
this is pure and cute.

2020-05-09 01:01 UTC, betoobernal commented on src/app/screens/book-list/book-list.component.ts
> +    ).subscribe()
Nooooope. :sad-harold:

```suggestion
    forkJoin({
      books: this.bookService.getBooks(),
      page: this.shoppingService.shoppingBooks
     }).subscribe(({ books, page })=>{
        this.shoppingBooks = books
        this.books = page
     })
```

2020-05-12 15:34 UTC, CrisVega08 commented on src/app/screens/book-list/book-list.component.ts
> +    forkJoin(
you combineLatest operator

2020-05-14 16:52 UTC, CrisVega08 approved these changes

2020-05-16 04:38 UTC, betoobernal commented on src/app/modules/auth/auth.component.ts
> +    this.shoppingService.shoppingBooks.pipe(takeUntil(this.destroySubject$)).subscribe(books => this.count = books.length);
indented
```suggestion
    this.shoppingService.shoppingBooks
         .pipe(takeUntil(this.destroySubject$))
         .subscribe(books => this.count = books.length);
```

2020-06-26 21:04 UTC, merged