Add book details with required styles
wolox-training/st-angular pull request #3
Opened 2020-04-07 22:42 UTC by blacksam07

## Summary
- Add view and styles to book detail

## Trello Card
[26-detalle-de-libro-i-textos](https://trello.com/c/GyM0nnnw/26-detalle-de-libro-i-textos)

## Screenshots

![image](https://user-images.githubusercontent.com/50454914/78726251-1c94f200-78f7-11ea-87ac-e8b4b3fcf5ee.png)

2020-04-07 22:49 UTC, betoobernal commented on index.html
> +    </div>
try to reduce the number of tags. I think that this `div` is unnecessary and `h1` tag is enough. Besides, use `span` tag instead of `p` tag.

2020-04-07 22:51 UTC, betoobernal commented on scss/detail.scss
> +  h1 {
use classes instead of a tag name

2020-04-07 22:51 UTC, betoobernal commented on scss/detail.scss
> +  p {
same

2020-04-07 22:51 UTC, betoobernal commented on scss/detail.scss
> +  h3 {
same

2020-04-07 22:51 UTC, betoobernal commented on scss/detail.scss
> +  p {
same

2020-04-08 00:02 UTC, CrisVega08 requested changes

2020-04-08 00:02 UTC, CrisVega08 commented on index.html
> +      <h1>Título del libro</h1><p>(género)</p>
what do you think ?? 
```suggestion
      <h1>Título del libro<span>(género)</span></h1>
```

2020-04-08 00:02 UTC, CrisVega08 commented on scss/detail.scss
> +  }
add empty line

2020-04-08 00:02 UTC, CrisVega08 commented on scss/detail.scss
> +  h1 {
add empty line

2020-04-08 00:02 UTC, CrisVega08 commented on scss/detail.scss
> +    color: #828282;
Sort properties alphabetics.

2020-04-08 00:02 UTC, CrisVega08 commented on scss/detail.scss
> +    color: #828282;
Create a file colors on src/variables/_color.scss and import here. 
Here define variables for colors you can use this page for color's names http://chir.ag/projects/name-that-color

2020-04-08 00:02 UTC, CrisVega08 commented on scss/detail.scss
> +  margin: 10px 10px;
```suggestion
  margin: 10px;
```

2020-04-08 00:02 UTC, CrisVega08 commented on scss/detail.scss
> +.item {
add empty line

2020-04-08 00:02 UTC, CrisVega08 commented on scss/detail.scss
> +
delete

2020-04-08 00:02 UTC, CrisVega08 commented on scss/detail.scss
> +    color: #828282;
sort properties and use variables

2020-04-08 00:02 UTC, CrisVega08 commented on scss/equalizer.scss
> +  font-family: Roboto;
For you roboto you must to import, use google fonts https://fonts.google.com/ and do this in OTHER FILE can be applications.scss no touch equalizer.scss

other thing is a good practice define second font.

2020-04-08 02:19 UTC, betoobernal commented on index.html
> +      <h1>Título del libro</h1><p>(género)</p>
the card wording is about Page Titles, Paragraph, Headings, Margin or padding. I would think that he did it well. 🤔

2020-04-08 15:18 UTC, betoobernal approved these changes

2020-04-08 15:26 UTC, CrisVega08 requested changes

2020-04-08 15:26 UTC, CrisVega08 commented on index.html
> +  <link  rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400&display=swap">
This work but I suggest use @import word on scss file 

@import url('https://fonts.googleapis.com/css2?family=Roboto:wght@300;400&display=swap');

other thing , what weights do you need only 300 and 400? think about it

2020-04-08 15:26 UTC, CrisVega08 commented on scss/application.scss
> +  font-family: 'Roboto';
Add second font for good practice 
```suggestion
  font-family: 'Roboto', sans-serif;
```

2020-04-08 15:26 UTC, CrisVega08 commented on scss/detail.scss
> +  margin-left: 10px;
sort properties

2020-04-08 15:45 UTC, betoobernal commented on scss/detail.scss
> +  color: $text-grey;
suggestion: colors name shall take the name own stand for itself. There exist a page for that. 
http://chir.ag/projects/name-that-color/#6195ED

2020-04-08 15:48 UTC, betoobernal commented on scss/detail.scss
> +  color: $text-grey;
Namely, the property **color** is declarative for its use.

2020-04-08 16:09 UTC, CrisVega08 requested changes

2020-04-08 16:09 UTC, CrisVega08 commented on index.html
> +    @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@100;400;700&display=swap');
🤦‍♂ in the applications.scss

2020-04-08 16:12 UTC, CrisVega08 commented
In the image there a problem with the line solve these 
![image](https://user-images.githubusercontent.com/26824183/78807512-ca50e100-7989-11ea-8ead-8d0d9ec810a5.png)

2020-04-08 16:51 UTC, betoobernal commented on index.html
> +    <h2 class="bold-title">Título del libro
tag div unnecessary. Apply 'top-item' class to the tag h2

2020-04-08 17:37 UTC, betoobernal approved these changes

2020-04-08 17:44 UTC, CrisVega08 approved these changes

2020-04-08 18:00 UTC, merged